import React, { useMemo, useState } from "react";
import moment from "moment";
import { Plus, Utensils, Search } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/components/ui/use-toast";
import { useWorkspace } from "@/lib/WorkspaceContext";
import PlayerPhoto from "@/components/player/PlayerPhoto";

const MEALS = ["Desayuno", "Media mañana", "Almuerzo", "Merienda", "Pre entrenamiento", "Durante entrenamiento", "Post entrenamiento", "Cena", "Colación nocturna"];
const ADHERENCE = [["muy_baja","Muy baja"],["baja","Baja"],["adecuada","Adecuada"],["muy_buena","Muy buena"]];
function playerName(p){return p?.full_name||`${p?.first_name||""} ${p?.last_name||""}`.trim()||"Jugador";}
function adherenceLabel(v){return ADHERENCE.find(([k])=>k===v)?.[1]||"—";}

export default function NutritionFoodDiaryView({ players = [], diaries = [], activeSquad, onReload }){
  const {can}=useWorkspace(); const canCreate=can("create","/performance/nutrition");
  const [creating,setCreating]=useState(false); const [query,setQuery]=useState(""); const [dateFilter,setDateFilter]=useState("");
  const playerMap=useMemo(()=>Object.fromEntries(players.map(p=>[p.id,p])),[players]);
  const rows=useMemo(()=>diaries.filter(d=>{const p=playerMap[d.player_id];if(query&&!playerName(p).toLowerCase().includes(query.toLowerCase()))return false;if(dateFilter&&d.log_date!==dateFilter)return false;return true;}).sort((a,b)=>String(b.log_date||"").localeCompare(String(a.log_date||""))),[diaries,playerMap,query,dateFilter]);
  return <div className="space-y-4">
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">Registro alimentario</p><h2 className="mt-2 text-xl font-bold">Alimentación del jugador</h2><p className="mt-1 max-w-3xl text-sm text-zinc-500">Usalo cuando haga falta registrar un día alimentario o revisar adherencia. No obliga a cargar comidas todos los días.</p></div>{canCreate&&<button onClick={()=>setCreating(true)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-zinc-900"><Plus size={15}/> Nuevo registro</button>}</div></section>
    <div className="flex flex-col gap-2 rounded-2xl border border-zinc-800 bg-zinc-900 p-3 md:flex-row"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar jugador..." className="border-zinc-700 bg-zinc-950 pl-9 text-white"/></div><Input type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)} className="w-full border-zinc-700 bg-zinc-950 text-white md:w-44"/></div>
    <div className="grid gap-4 xl:grid-cols-2">{rows.map(d=>{const p=playerMap[d.player_id];return <section key={d.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><PlayerPhoto player={p||{full_name:d.player_name}} className="h-10 w-10 rounded-full border border-zinc-700 object-cover" fallbackClassName="flex h-10 w-10 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800"/><div><p className="font-bold text-white">{playerName(p)||d.player_name}</p><p className="text-xs text-zinc-500">{moment(d.log_date).format("DD/MM/YYYY")}</p></div></div><span className="rounded-full border border-zinc-700 bg-zinc-950 px-2.5 py-1 text-xs text-zinc-300">Adh. {adherenceLabel(d.adherence)}</span></div><div className="mt-4 space-y-2">{(d.meals||[]).filter(m=>m.description).map((meal,index)=><div key={`${meal.type}-${index}`} className="grid grid-cols-[130px_1fr] gap-3 rounded-xl bg-zinc-950 p-3"><p className="text-xs font-semibold text-emerald-300">{meal.type}{meal.time?` · ${meal.time}`:""}</p><div><p className="text-sm text-zinc-300">{meal.description}</p>{meal.quantity_notes&&<p className="mt-1 text-xs text-zinc-600">{meal.quantity_notes}</p>}</div></div>)}{!(d.meals||[]).some(m=>m.description)&&<p className="text-sm text-zinc-600">Sin detalle de comidas.</p>}</div>{d.gi_symptoms&&<p className="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/5 px-3 py-2 text-xs text-amber-300">Síntomas GI: {(d.gi_symptom_types||[]).join(", ")||"registrados"}</p>}{d.notes&&<p className="mt-3 text-xs leading-5 text-zinc-500">{d.notes}</p>}</section>})}{!rows.length&&<div className="xl:col-span-2 rounded-2xl border border-dashed border-zinc-800 p-12 text-center text-zinc-600">No hay registros alimentarios con estos filtros.</div>}</div>
    {creating&&<FoodDiaryModal players={players} activeSquad={activeSquad} onClose={()=>setCreating(false)} onSaved={()=>{setCreating(false);onReload?.();}}/>}
  </div>;
}

function FoodDiaryModal({players,activeSquad,onClose,onSaved}){
  const [form,setForm]=useState({player_id:"",log_date:moment().format("YYYY-MM-DD"),appetite:"normal",adherence:"adecuada",gi_symptoms:false,gi_symptom_types:"",notes:"",meals:MEALS.map(type=>({type,time:"",description:"",quantity_notes:""}))}); const [saving,setSaving]=useState(false); const {toast}=useToast(); const sorted=[...players].sort((a,b)=>playerName(a).localeCompare(playerName(b))); const input="border-zinc-700 bg-zinc-800 text-white";
  const patchMeal=(index,key,value)=>setForm(f=>({...f,meals:f.meals.map((m,i)=>i===index?{...m,[key]:value}:m)}));
  async function save(e){e.preventDefault();const p=sorted.find(x=>x.id===form.player_id);if(!p)return;setSaving(true);try{const user=await base44.auth.me();const now=new Date().toISOString();await base44.entities.NutritionFoodDiary.create({club_id:p.club_id||"",squad_id:activeSquad?.id||p.squad_id||"",season_id:String(activeSquad?.season||p.season_id||""),player_id:p.id,player_name:playerName(p),log_date:form.log_date,source:"staff",meals:form.meals.filter(m=>m.description||m.quantity_notes),appetite:form.appetite,adherence:form.adherence,gi_symptoms:form.gi_symptoms,gi_symptom_types:form.gi_symptoms?form.gi_symptom_types.split(",").map(x=>x.trim()).filter(Boolean):[],notes:form.notes,created_by_name:user?.full_name||user?.email||"Usuario",created_at:now,updated_at:now});toast({title:"Registro alimentario guardado",description:playerName(p)});onSaved();}catch(error){toast({title:"No se pudo guardar",description:error?.message,variant:"destructive"});}finally{setSaving(false);}}
  return <Dialog open onOpenChange={onClose}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto border-zinc-800 bg-zinc-900 text-white"><DialogHeader><DialogTitle>Nuevo registro alimentario</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-5"><div className="grid gap-3 md:grid-cols-4"><div><label className="mb-1 block text-xs text-zinc-400">Jugador *</label><Select value={form.player_id} onValueChange={v=>setForm(f=>({...f,player_id:v}))}><SelectTrigger className={input}><SelectValue placeholder="Seleccionar"/></SelectTrigger><SelectContent className="border-zinc-700 bg-zinc-900">{sorted.map(p=><SelectItem key={p.id} value={p.id} className="text-white">{playerName(p)}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1 block text-xs text-zinc-400">Fecha</label><Input type="date" value={form.log_date} onChange={e=>setForm(f=>({...f,log_date:e.target.value}))} className={input}/></div><div><label className="mb-1 block text-xs text-zinc-400">Apetito</label><select value={form.appetite} onChange={e=>setForm(f=>({...f,appetite:e.target.value}))} className="h-10 w-full rounded-md border border-zinc-700 bg-zinc-800 px-3 text-sm"><option value="muy_bajo">Muy bajo</option><option value="bajo">Bajo</option><option value="normal">Normal</option><option value="alto">Alto</option><option value="muy_alto">Muy alto</option></select></div><div><label className="mb-1 block text-xs text-zinc-400">Adherencia</label><select value={form.adherence} onChange={e=>setForm(f=>({...f,adherence:e.target.value}))} className="h-10 w-full rounded-md border border-zinc-700 bg-zinc-800 px-3 text-sm">{ADHERENCE.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
  <section><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Comidas del día</p><div className="space-y-2">{form.meals.map((meal,index)=><div key={meal.type} className="grid gap-2 rounded-xl border border-zinc-800 bg-zinc-950/50 p-3 md:grid-cols-[150px_100px_1fr_1fr]"><div className="flex items-center gap-2 text-xs font-semibold text-emerald-300"><Utensils size={13}/>{meal.type}</div><Input type="time" value={meal.time} onChange={e=>patchMeal(index,"time",e.target.value)} className={input}/><Input value={meal.description} onChange={e=>patchMeal(index,"description",e.target.value)} placeholder="Alimentos / preparación" className={input}/><Input value={meal.quantity_notes} onChange={e=>patchMeal(index,"quantity_notes",e.target.value)} placeholder="Cantidad / observación" className={input}/></div>)}</div></section>
  <label className="flex items-center gap-2 text-sm text-zinc-400"><input type="checkbox" checked={form.gi_symptoms} onChange={e=>setForm(f=>({...f,gi_symptoms:e.target.checked}))}/> Hubo molestias gastrointestinales</label>{form.gi_symptoms&&<Input value={form.gi_symptom_types} onChange={e=>setForm(f=>({...f,gi_symptom_types:e.target.value}))} placeholder="Ej: distensión, reflujo, náuseas" className={input}/>}<Textarea rows={3} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Observaciones del nutricionista" className="border-zinc-700 bg-zinc-800 text-white"/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose} className="border-zinc-700 text-zinc-300">Cancelar</Button><Button disabled={saving||!form.player_id} className="bg-white text-zinc-900">{saving?"Guardando...":"Guardar registro"}</Button></div></form></DialogContent></Dialog>;
}
