import React, { useMemo } from "react";
import moment from "moment";
import { Droplets, Gauge, Thermometer } from "lucide-react";
import PlayerPhoto from "@/components/player/PlayerPhoto";

function playerName(p){return p?.full_name||`${p?.first_name||""} ${p?.last_name||""}`.trim()||"Jugador";}
function fmt(v,d=2){return v==null||v===""?"—":Number(v).toFixed(d);}

export default function NutritionHydrationView({ players = [], controls = [] }){
  const playerMap=useMemo(()=>Object.fromEntries(players.map(p=>[p.id,p])),[players]);
  const rows=useMemo(()=>controls.filter(c=>c.hydration_measured).sort((a,b)=>String(b.control_date||"").localeCompare(String(a.control_date||""))),[controls]);
  const latestByPlayer=useMemo(()=>{const m={};rows.forEach(r=>{if(!m[r.player_id])m[r.player_id]=r;});return Object.values(m);},[rows]);
  const withSweatRate=rows.filter(r=>Number.isFinite(Number(r.sweat_rate_l_h)));
  const avgSweatRate=withSweatRate.length?withSweatRate.reduce((s,r)=>s+Number(r.sweat_rate_l_h),0)/withSweatRate.length:null;
  return <div className="space-y-4">
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Controles opcionales</p><h2 className="mt-2 text-xl font-bold">Hidratación</h2><p className="mt-1 max-w-3xl text-sm text-zinc-500">La hidratación se registra solamente cuando se mide. PerformancePitch calcula cambio de masa corporal, pérdida estimada de líquido y tasa de sudoración cuando existen los datos necesarios.</p></section>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Card icon={Droplets} label="Controles registrados" value={rows.length}/><Card icon={Gauge} label="Jugadores con dato" value={latestByPlayer.length}/><Card icon={Droplets} label="Tasa media registrada" value={avgSweatRate==null?"—":`${avgSweatRate.toFixed(2)} L/h`}/><Card icon={Thermometer} label="Último control" value={rows[0]?.control_date?moment(rows[0].control_date).format("DD/MM"):"—"}/></div>
    <section className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900"><div className="border-b border-zinc-800 p-4"><h3 className="font-bold">Historial de hidratación</h3><p className="text-xs text-zinc-600">No se aplican clasificaciones automáticas universales; se muestran los datos y su contexto para interpretación profesional.</p></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead className="bg-zinc-950/60 text-left text-[10px] uppercase tracking-wide text-zinc-600"><tr><th className="p-3">Jugador</th><th className="p-3">Fecha</th><th className="p-3">Peso pre</th><th className="p-3">Peso post</th><th className="p-3">Δ masa</th><th className="p-3">Líquido</th><th className="p-3">Pérdida est.</th><th className="p-3">Sudoración</th><th className="p-3">USG</th><th className="p-3">Temp.</th></tr></thead><tbody>{rows.map(r=>{const p=playerMap[r.player_id];return <tr key={r.id} className="border-t border-zinc-800/70 hover:bg-zinc-800/25"><td className="p-3"><div className="flex items-center gap-2"><PlayerPhoto player={p||{full_name:r.player_name}} className="h-8 w-8 rounded-full border border-zinc-700 object-cover" fallbackClassName="flex h-8 w-8 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800"/><span className="font-semibold text-zinc-200">{playerName(p)||r.player_name}</span></div></td><td className="p-3 text-zinc-400">{moment(r.control_date).format("DD/MM/YYYY")}</td><td className="p-3 text-zinc-300">{r.pre_weight_kg!=null?`${fmt(r.pre_weight_kg,1)} kg`:"—"}</td><td className="p-3 text-zinc-300">{r.post_weight_kg!=null?`${fmt(r.post_weight_kg,1)} kg`:"—"}</td><td className="p-3 font-semibold text-cyan-300">{r.body_mass_change_pct!=null?`${fmt(r.body_mass_change_pct,2)}%`:"—"}</td><td className="p-3 text-zinc-300">{r.fluid_intake_ml!=null?`${Math.round(Number(r.fluid_intake_ml))} ml`:"—"}</td><td className="p-3 text-zinc-300">{r.estimated_sweat_loss_l!=null?`${fmt(r.estimated_sweat_loss_l,2)} L`:"—"}</td><td className="p-3 font-semibold text-cyan-300">{r.sweat_rate_l_h!=null?`${fmt(r.sweat_rate_l_h,2)} L/h`:"—"}</td><td className="p-3 text-zinc-300">{r.urine_specific_gravity!=null?fmt(r.urine_specific_gravity,3):"—"}</td><td className="p-3 text-zinc-300">{r.temperature_c!=null?`${fmt(r.temperature_c,1)}°`:"—"}</td></tr>})}{!rows.length&&<tr><td colSpan={10} className="p-12 text-center text-zinc-600">Todavía no hay controles de hidratación.</td></tr>}</tbody></table></div></section>
  </div>;
}
function Card({icon:Icon,label,value}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center justify-between"><p className="text-xs text-zinc-500">{label}</p><Icon size={16} className="text-cyan-300"/></div><p className="mt-2 text-2xl font-bold text-white">{value}</p></div>}
