import React, { useMemo } from "react";
import moment from "moment";
import { AlertTriangle, CalendarClock, ClipboardCheck, ClipboardList, Scale, Users } from "lucide-react";
import PlayerPhoto from "@/components/player/PlayerPhoto";

function playerName(p){return p?.full_name||`${p?.first_name||""} ${p?.last_name||""}`.trim()||"Jugador";}
function latestMap(rows,dateField){const map={};rows.forEach(r=>{if(!r.player_id)return;const current=map[r.player_id];if(!current||String(r[dateField]||"")>String(current[dateField]||""))map[r.player_id]=r;});return map;}
function monitoringStatus(m){if(m.status==="paused"||m.status==="cancelled")return m.status;if(m.end_date&&moment(m.end_date).endOf("day").isBefore(moment().startOf("day")))return "completed";return m.status||"active";}

export default function NutritionOverviewDashboard({players=[],controls=[],assessments=[],monitorings=[],weightEntries=[],plans=[],diaries=[]}){
  const playerMap=useMemo(()=>Object.fromEntries(players.map(p=>[p.id,p])),[players]);
  const latestControls=useMemo(()=>latestMap(controls,"control_date"),[controls]);
  const latestAssessments=useMemo(()=>latestMap(assessments,"fecha"),[assessments]);
  const activeMonitorings=useMemo(()=>monitorings.filter(m=>monitoringStatus(m)==="active"),[monitorings]);
  const activePlans=useMemo(()=>plans.filter(p=>p.status==="active"),[plans]);
  const controlled30=useMemo(()=>players.filter(p=>{const c=latestControls[p.id];const a=latestAssessments[p.id];const dates=[c?.control_date,a?.fecha].filter(Boolean).map(d=>moment(d));return dates.some(d=>moment().diff(d,"days")<=30);}).length,[players,latestControls,latestAssessments]);
  const dueControls=useMemo(()=>controls.filter(c=>c.next_control_date&&moment(c.next_control_date).endOf("day").isBefore(moment())).sort((a,b)=>String(a.next_control_date).localeCompare(String(b.next_control_date))),[controls]);
  const entryByMonitoring=useMemo(()=>{const map={};weightEntries.forEach(e=>{if(!map[e.monitoring_id])map[e.monitoring_id]=[];map[e.monitoring_id].push(e);});return map;},[weightEntries]);
  const attention=useMemo(()=>{
    const items=[];
    dueControls.slice(0,8).forEach(c=>items.push({player_id:c.player_id,kind:"Control vencido",detail:`Próximo control previsto ${moment(c.next_control_date).format("DD/MM")}`,tone:"amber"}));
    activeMonitorings.forEach(m=>{const entries=(entryByMonitoring[m.id]||[]).sort((a,b)=>String(b.entry_date).localeCompare(String(a.entry_date)));const last=entries[0];const daysSince=last?moment().diff(moment(last.entry_date),"days"):999;if(daysSince>=2)items.push({player_id:m.player_id,kind:"Peso pendiente",detail:last?`${daysSince} días sin registro en seguimiento activo`:"Seguimiento activo sin registros",tone:"amber"});});
    Object.values(latestControls).forEach(c=>{if(["ajustar_plan","citar_jugador","derivar"].includes(c.intervention))items.push({player_id:c.player_id,kind:"Intervención",detail:c.intervention==="ajustar_plan"?"Requiere ajustar plan":c.intervention==="citar_jugador"?"Citar jugador":"Derivación registrada",tone:"red"});if(c.plan_adherence==="baja"||c.plan_adherence==="muy_baja")items.push({player_id:c.player_id,kind:"Adherencia",detail:`Adherencia ${c.plan_adherence.replace("_"," ")}`,tone:"amber"});if(c.gi_symptoms)items.push({player_id:c.player_id,kind:"Síntomas GI",detail:(c.gi_symptom_types||[]).join(", ")||"Síntomas gastrointestinales registrados",tone:"amber"});});
    const seen=new Set();return items.filter(i=>{const key=`${i.player_id}|${i.kind}`;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,12);
  },[dueControls,activeMonitorings,entryByMonitoring,latestControls]);

  const recent=useMemo(()=>players.map(p=>{const c=latestControls[p.id];const a=latestAssessments[p.id];const cDate=c?.control_date||"";const aDate=a?.fecha||"";const latestDate=cDate>=aDate?cDate:aDate;const weight=cDate>=aDate?(c?.weight_kg??a?.peso):(a?.peso??c?.weight_kg);const plan=activePlans.find(x=>x.player_id===p.id);const monitoring=activeMonitorings.find(x=>x.player_id===p.id);return {player:p,latestDate,weight,plan,monitoring,next:c?.next_control_date};}).sort((a,b)=>String(b.latestDate).localeCompare(String(a.latestDate))),[players,latestControls,latestAssessments,activePlans,activeMonitorings]);

  return <div className="space-y-5">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Card icon={Users} label="Plantel activo" value={players.length}/><Card icon={ClipboardCheck} label="Controlados 30 días" value={`${controlled30}/${players.length}`}/><Card icon={Scale} label="Seguimientos de peso" value={activeMonitorings.length}/><Card icon={ClipboardList} label="Planes activos" value={activePlans.length}/><Card icon={CalendarClock} label="Controles vencidos" value={dueControls.length} tone={dueControls.length?"amber":"zinc"}/></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,0.8fr)]">
      <section className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900"><div className="border-b border-zinc-800 p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-zinc-500">Vista del plantel</p><h2 className="mt-1 font-bold text-white">Seguimiento nutricional</h2><p className="mt-1 text-xs text-zinc-600">Último control, peso, plan y seguimiento temporal en una misma vista.</p></div><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead className="bg-zinc-950/60 text-left text-[10px] uppercase tracking-wide text-zinc-600"><tr><th className="p-3">Jugador</th><th className="p-3">Último control</th><th className="p-3">Peso</th><th className="p-3">Plan</th><th className="p-3">Seguimiento peso</th><th className="p-3">Próximo control</th></tr></thead><tbody>{recent.map(r=><tr key={r.player.id} className="border-t border-zinc-800/70 hover:bg-zinc-800/25"><td className="p-3"><div className="flex items-center gap-2"><PlayerPhoto player={r.player} className="h-9 w-9 rounded-full border border-zinc-700 object-cover" fallbackClassName="flex h-9 w-9 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800"/><div><p className="font-semibold text-zinc-200">{playerName(r.player)}</p><p className="text-[10px] text-zinc-600">{r.player.position||""}</p></div></div></td><td className="p-3 text-zinc-400">{r.latestDate?moment(r.latestDate).format("DD/MM/YYYY"):"Sin control"}</td><td className="p-3 font-bold text-white">{r.weight!=null?`${Number(r.weight).toFixed(1)} kg`:"—"}</td><td className="p-3">{r.plan?<span className="rounded-full border border-emerald-500/25 bg-emerald-500/10 px-2 py-1 text-xs text-emerald-300">Activo</span>:<span className="text-zinc-700">Sin plan</span>}</td><td className="p-3">{r.monitoring?<span className="rounded-full border border-blue-500/25 bg-blue-500/10 px-2 py-1 text-xs text-blue-300">Activo hasta {moment(r.monitoring.end_date).format("DD/MM")}</span>:<span className="text-zinc-700">No activo</span>}</td><td className={`p-3 ${r.next&&moment(r.next).endOf("day").isBefore(moment())?"font-semibold text-amber-300":"text-zinc-400"}`}>{r.next?moment(r.next).format("DD/MM/YYYY"):"—"}</td></tr>)}</tbody></table></div></section>
      <aside className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-zinc-500">Requieren atención</p><p className="mt-1 text-xs text-zinc-600">Motivos explícitos, no un score opaco.</p></div><AlertTriangle size={18} className="text-amber-400"/></div><div className="mt-4 space-y-2">{attention.map((item,index)=>{const p=playerMap[item.player_id];return <div key={`${item.player_id}-${item.kind}-${index}`} className={`rounded-xl border p-3 ${item.tone==="red"?"border-red-500/20 bg-red-500/5":"border-amber-500/20 bg-amber-500/5"}`}><div className="flex items-center gap-2"><PlayerPhoto player={p||{}} className="h-8 w-8 rounded-full border border-zinc-700 object-cover" fallbackClassName="flex h-8 w-8 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800"/><div className="min-w-0"><p className="truncate text-sm font-semibold text-zinc-200">{playerName(p)}</p><p className={`text-[10px] font-semibold uppercase ${item.tone==="red"?"text-red-300":"text-amber-300"}`}>{item.kind}</p></div></div><p className="mt-2 text-xs leading-5 text-zinc-500">{item.detail}</p></div>})}{!attention.length&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">No hay acciones pendientes detectadas con los datos disponibles.</div>}</div></aside>
    </div>
  </div>;
}
function Card({icon:Icon,label,value,tone="zinc"}){const cls=tone==="amber"?"border-amber-500/25 bg-amber-500/[0.05]":"border-zinc-800 bg-zinc-900";return <div className={`rounded-2xl border p-4 ${cls}`}><div className="flex items-center justify-between"><p className="text-xs text-zinc-500">{label}</p><Icon size={16} className={tone==="amber"?"text-amber-300":"text-emerald-300"}/></div><p className="mt-2 text-3xl font-bold text-white">{value}</p></div>}
