import React, { useMemo, useState } from "react";
import moment from "moment";
import { Plus, ClipboardList, Dumbbell, UtensilsCrossed, Droplets } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/components/ui/use-toast";
import { useWorkspace } from "@/lib/WorkspaceContext";
import PlayerPhoto from "@/components/player/PlayerPhoto";

const OBJECTIVES = [
  ["maintain", "Mantener composición"], ["muscle_gain", "Ganancia de masa muscular"], ["fat_reduction", "Reducir masa grasa"],
  ["recovery", "Optimizar recuperación"], ["competition", "Estrategia de competición"], ["rehab", "Rehabilitación / retorno"],
  ["education", "Educación alimentaria"], ["other", "Otro"],
];
function playerName(p){return p?.full_name||`${p?.first_name||""} ${p?.last_name||""}`.trim()||"Jugador";}
function objectiveLabel(v){return OBJECTIVES.find(([k])=>k===v)?.[1]||v||"—";}

export default function NutritionPlanManager({ players = [], plans = [], activeSquad, onReload }) {
  const { can } = useWorkspace(); const canCreate=can("create","/performance/nutrition"); const canEdit=can("edit","/performance/nutrition");
  const [creating,setCreating]=useState(false); const [editing,setEditing]=useState(null); const [showClosed,setShowClosed]=useState(false);
  const playerMap=useMemo(()=>Object.fromEntries(players.map(p=>[p.id,p])),[players]);
  const rows=useMemo(()=>plans.filter(p=>showClosed||p.status==="active"||p.status==="paused").sort((a,b)=>String(b.start_date||"").localeCompare(String(a.start_date||""))),[plans,showClosed]);
  const activeCount=plans.filter(p=>p.status==="active").length;
  return <div className="space-y-4">
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">Intervención individual</p><h2 className="mt-2 text-xl font-bold">Planes nutricionales</h2><p className="mt-1 max-w-3xl text-sm text-zinc-500">Objetivos, macronutrientes opcionales, hidratación y estrategias según entrenamiento, partido y recuperación.</p></div><div className="flex gap-2"><div className="rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-2"><p className="text-[10px] text-zinc-600">Planes activos</p><p className="text-xl font-bold text-emerald-300">{activeCount}</p></div>{canCreate&&<button onClick={()=>setCreating(true)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-zinc-900"><Plus size={15}/> Nuevo plan</button>}</div></div></section>
    <div className="flex justify-end"><label className="flex items-center gap-2 text-xs text-zinc-500"><input type="checkbox" checked={showClosed} onChange={e=>setShowClosed(e.target.checked)}/> Mostrar finalizados</label></div>
    <div className="grid gap-4 xl:grid-cols-2">{rows.map(plan=>{const p=playerMap[plan.player_id];return <section key={plan.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><PlayerPhoto player={p||{full_name:plan.player_name}} className="h-11 w-11 rounded-full border border-zinc-700 object-cover" fallbackClassName="flex h-11 w-11 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800"/><div><p className="font-bold text-white">{playerName(p)||plan.player_name}</p><p className="text-xs text-zinc-500">{objectiveLabel(plan.objective)}</p></div></div><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${plan.status==="active"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":plan.status==="paused"?"border-amber-500/30 bg-amber-500/10 text-amber-300":"border-zinc-700 bg-zinc-800 text-zinc-400"}`}>{plan.status==="active"?"Activo":plan.status==="paused"?"Pausado":"Finalizado"}</span></div>
      <div className="mt-4 grid grid-cols-4 gap-2"><Metric label="CHO" value={plan.carbs_g_kg!=null?`${plan.carbs_g_kg} g/kg`:"—"}/><Metric label="Proteína" value={plan.protein_g_kg!=null?`${plan.protein_g_kg} g/kg`:"—"}/><Metric label="Grasas" value={plan.fat_g_kg!=null?`${plan.fat_g_kg} g/kg`:"—"}/><Metric label="Hidratación" value={plan.hydration_target_ml!=null?`${plan.hydration_target_ml} ml`:"—"}/></div>
      <div className="mt-3 grid gap-2 sm:grid-cols-3"><Strategy icon={Dumbbell} label="Pre entrenamiento" text={plan.pre_training_strategy}/><Strategy icon={UtensilsCrossed} label="Partido" text={plan.match_day_strategy}/><Strategy icon={Droplets} label="Recuperación" text={plan.post_training_strategy||plan.md_plus_1_strategy}/></div>
      <div className="mt-3 flex items-center justify-between border-t border-zinc-800 pt-3"><p className="text-xs text-zinc-600">Desde {plan.start_date?moment(plan.start_date).format("DD/MM/YYYY"):"—"}{plan.end_date?` · hasta ${moment(plan.end_date).format("DD/MM/YYYY")}`:""}</p>{canEdit&&<button onClick={()=>setEditing(plan)} className="rounded-lg border border-zinc-700 px-3 py-1.5 text-xs font-semibold text-zinc-300 hover:text-white">Editar plan</button>}</div>
    </section>})}{!rows.length&&<div className="xl:col-span-2 rounded-2xl border border-dashed border-zinc-800 p-12 text-center text-zinc-600">Todavía no hay planes nutricionales.</div>}</div>
    {(creating||editing)&&<PlanModal plan={editing} players={players} activeSquad={activeSquad} onClose={()=>{setCreating(false);setEditing(null);}} onSaved={()=>{setCreating(false);setEditing(null);onReload?.();}}/>}
  </div>;
}
function Metric({label,value}){return <div className="rounded-xl bg-zinc-950 p-3"><p className="text-[10px] text-zinc-600">{label}</p><p className="mt-1 text-sm font-bold text-zinc-200">{value}</p></div>}
function Strategy({icon:Icon,label,text}){return <div className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><p className="flex items-center gap-1 text-[10px] uppercase text-zinc-600"><Icon size={12}/>{label}</p><p className="mt-1 line-clamp-3 text-xs leading-5 text-zinc-300">{text||"Sin estrategia cargada"}</p></div>}

function PlanModal({plan,players,activeSquad,onClose,onSaved}){
  const [form,setForm]=useState({player_id:plan?.player_id||"",status:plan?.status||"active",start_date:plan?.start_date||moment().format("YYYY-MM-DD"),end_date:plan?.end_date||"",objective:plan?.objective||"maintain",objective_notes:plan?.objective_notes||"",energy_kcal:plan?.energy_kcal??"",carbs_g_kg:plan?.carbs_g_kg??"",protein_g_kg:plan?.protein_g_kg??"",fat_g_kg:plan?.fat_g_kg??"",hydration_target_ml:plan?.hydration_target_ml??"",breakfast_strategy:plan?.breakfast_strategy||"",lunch_strategy:plan?.lunch_strategy||"",snack_strategy:plan?.snack_strategy||"",dinner_strategy:plan?.dinner_strategy||"",pre_training_strategy:plan?.pre_training_strategy||"",during_training_strategy:plan?.during_training_strategy||"",post_training_strategy:plan?.post_training_strategy||"",md_minus_1_strategy:plan?.md_minus_1_strategy||"",match_day_strategy:plan?.match_day_strategy||"",md_plus_1_strategy:plan?.md_plus_1_strategy||"",notes:plan?.notes||"",private_notes:plan?.private_notes||""});
  const [saving,setSaving]=useState(false);const {toast}=useToast();const sorted=[...players].sort((a,b)=>playerName(a).localeCompare(playerName(b)));const input="border-zinc-700 bg-zinc-800 text-white";
  const patch=(k,v)=>setForm(f=>({...f,[k]:v}));
  async function save(e){e.preventDefault();const p=sorted.find(x=>x.id===form.player_id);if(!p)return;setSaving(true);try{const user=await base44.auth.me();const now=new Date().toISOString();const payload={club_id:p.club_id||"",squad_id:activeSquad?.id||p.squad_id||"",season_id:String(activeSquad?.season||p.season_id||""),player_id:p.id,player_name:playerName(p),status:form.status,start_date:form.start_date,end_date:form.end_date||undefined,objective:form.objective,objective_notes:form.objective_notes,energy_kcal:form.energy_kcal===""?undefined:Number(form.energy_kcal),carbs_g_kg:form.carbs_g_kg===""?undefined:Number(form.carbs_g_kg),protein_g_kg:form.protein_g_kg===""?undefined:Number(form.protein_g_kg),fat_g_kg:form.fat_g_kg===""?undefined:Number(form.fat_g_kg),hydration_target_ml:form.hydration_target_ml===""?undefined:Number(form.hydration_target_ml),breakfast_strategy:form.breakfast_strategy,lunch_strategy:form.lunch_strategy,snack_strategy:form.snack_strategy,dinner_strategy:form.dinner_strategy,pre_training_strategy:form.pre_training_strategy,during_training_strategy:form.during_training_strategy,post_training_strategy:form.post_training_strategy,md_minus_1_strategy:form.md_minus_1_strategy,match_day_strategy:form.match_day_strategy,md_plus_1_strategy:form.md_plus_1_strategy,notes:form.notes,private_notes:form.private_notes,responsible_name:user?.full_name||user?.email||"Usuario",updated_at:now};Object.keys(payload).forEach(k=>payload[k]===undefined&&delete payload[k]);if(plan?.id)await base44.entities.NutritionPlan.update(plan.id,payload);else await base44.entities.NutritionPlan.create({...payload,created_by_name:user?.full_name||user?.email||"Usuario",created_at:now});toast({title:plan?"Plan actualizado":"Plan creado",description:playerName(p)});onSaved();}catch(error){toast({title:"No se pudo guardar el plan",description:error?.message,variant:"destructive"});}finally{setSaving(false);}}
  return <Dialog open onOpenChange={onClose}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto border-zinc-800 bg-zinc-900 text-white"><DialogHeader><DialogTitle>{plan?"Editar":"Nuevo"} plan nutricional</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-5"><div className="grid gap-3 md:grid-cols-4"><div><label className="mb-1 block text-xs text-zinc-400">Jugador *</label><Select disabled={!!plan} value={form.player_id} onValueChange={v=>patch("player_id",v)}><SelectTrigger className={input}><SelectValue placeholder="Seleccionar"/></SelectTrigger><SelectContent className="border-zinc-700 bg-zinc-900">{sorted.map(p=><SelectItem key={p.id} value={p.id} className="text-white">{playerName(p)}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1 block text-xs text-zinc-400">Objetivo</label><Select value={form.objective} onValueChange={v=>patch("objective",v)}><SelectTrigger className={input}><SelectValue/></SelectTrigger><SelectContent className="border-zinc-700 bg-zinc-900">{OBJECTIVES.map(([v,l])=><SelectItem key={v} value={v} className="text-white">{l}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1 block text-xs text-zinc-400">Inicio</label><Input type="date" value={form.start_date} onChange={e=>patch("start_date",e.target.value)} className={input}/></div><div><label className="mb-1 block text-xs text-zinc-400">Estado</label><select value={form.status} onChange={e=>patch("status",e.target.value)} className="h-10 w-full rounded-md border border-zinc-700 bg-zinc-800 px-3 text-sm"><option value="active">Activo</option><option value="paused">Pausado</option><option value="completed">Finalizado</option></select></div></div>
  <div><label className="mb-1 block text-xs text-zinc-400">Objetivo / contexto</label><Textarea rows={2} value={form.objective_notes} onChange={e=>patch("objective_notes",e.target.value)} className="border-zinc-700 bg-zinc-800 text-white"/></div>
  <section><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Objetivos cuantitativos opcionales</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["energy_kcal","Energía (kcal)"],["carbs_g_kg","CHO (g/kg)"],["protein_g_kg","Proteína (g/kg)"],["fat_g_kg","Grasas (g/kg)"],["hydration_target_ml","Hidratación (ml)"]].map(([k,l])=><div key={k}><label className="mb-1 block text-xs text-zinc-400">{l}</label><Input type="number" step="0.1" value={form[k]} onChange={e=>patch(k,e.target.value)} className={input}/></div>)}</div></section>
  <section><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Estrategia diaria</p><div className="grid gap-3 md:grid-cols-2">{[["breakfast_strategy","Desayuno"],["lunch_strategy","Almuerzo"],["snack_strategy","Merienda / colaciones"],["dinner_strategy","Cena"]].map(([k,l])=><div key={k}><label className="mb-1 block text-xs text-zinc-400">{l}</label><Textarea rows={2} value={form[k]} onChange={e=>patch(k,e.target.value)} className="border-zinc-700 bg-zinc-800 text-white"/></div>)}</div></section>
  <section><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Entrenamiento y recuperación</p><div className="grid gap-3 md:grid-cols-3">{[["pre_training_strategy","Pre entrenamiento"],["during_training_strategy","Durante"],["post_training_strategy","Post entrenamiento"]].map(([k,l])=><div key={k}><label className="mb-1 block text-xs text-zinc-400">{l}</label><Textarea rows={3} value={form[k]} onChange={e=>patch(k,e.target.value)} className="border-zinc-700 bg-zinc-800 text-white"/></div>)}</div></section>
  <section><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Microciclo / partido</p><div className="grid gap-3 md:grid-cols-3">{[["md_minus_1_strategy","MD-1"],["match_day_strategy","Día de partido"],["md_plus_1_strategy","MD+1"]].map(([k,l])=><div key={k}><label className="mb-1 block text-xs text-zinc-400">{l}</label><Textarea rows={3} value={form[k]} onChange={e=>patch(k,e.target.value)} className="border-zinc-700 bg-zinc-800 text-white"/></div>)}</div></section>
  <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose} className="border-zinc-700 text-zinc-300">Cancelar</Button><Button disabled={saving||!form.player_id} className="bg-white text-zinc-900"><ClipboardList size={15} className="mr-2"/>{saving?"Guardando...":"Guardar plan"}</Button></div></form></DialogContent></Dialog>;
}
