import {
  ShieldCheck, LayoutDashboard, ClipboardList, Gauge,
  Heart, UserRound, Network, Trophy, CalendarDays,
} from 'lucide-react';

export const DEMO_STAGES = [
  {
    id: 'vision',
    title: 'Visión del club',
    short: 'Visión del club',
    route: '/club-dashboard',
    icon: ShieldCheck,
    message: 'Toda la información competitiva del club en un mismo lugar.',
    text: 'PerformancePitch puede integrar las competencias que disputa cada plantel y centralizar fixtures, resultados, posiciones y próximos compromisos.',
    hints: [
      'Cambiá de competencia para consultar cada torneo desde el mismo entorno.',
      'Próximos partidos, resultados y tablas pueden actualizarse desde las fuentes conectadas al club.',
      'La misma estructura puede organizar Primera, Reserva y categorías juveniles.',
    ],
  },
  {
    id: 'operacion',
    title: 'Operación diaria',
    short: 'Operación diaria',
    route: '/dashboard',
    icon: LayoutDashboard,
    message: 'El estado del plantel, actualizado para todo el equipo de trabajo.',
    text: 'Disponibilidad, lesiones, trabajos diferenciados, movimientos entre planteles y actividad diaria conectados en un mismo entorno.',
    hints: [
      'Acá podés ver rápidamente la disponibilidad del plantel.',
      'Lesiones y trabajos diferenciados se ven en un mismo lugar.',
    ],
  },
  {
    id: 'partidos',
    title: 'Partidos',
    short: 'Partidos',
    route: '/matches',
    icon: Trophy,
    message: 'Cada partido conecta convocatoria, formación, minutos y rendimiento.',
    text: 'Recorré un encuentro completo con convocatoria, formación y datos GPS ya cargados.',
    hints: [
      'Abrí el partido finalizado para recorrer el ejemplo completo.',
      'La convocatoria alimenta formación, minutos y análisis individual.',
      'El GPS queda asociado al jugador y al contexto competitivo.',
    ],
  },
  {
    id: 'calendario',
    title: 'Calendario',
    short: 'Calendario',
    route: '/schedule',
    icon: CalendarDays,
    message: 'Toda la operación del plantel ordenada en una única agenda.',
    text: 'Entrenamientos, comidas, video, logística y partidos conectados con el resto de la plataforma.',
    hints: [
      'Alterná entre semana y mes.',
      'Filtrá por tipo de actividad.',
      'El partido del calendario se conecta con su ficha competitiva.',
    ],
  },
  {
    id: 'planificacion',
    title: 'Planificación',
    short: 'Planificación',
    route: '/weekly-planner',
    icon: ClipboardList,
    message: 'Toda la semana se construye alrededor del próximo desafío competitivo.',
    text: 'PerformancePitch conecta calendario, sesiones, cargas y disponibilidad para que las diferentes áreas trabajen sobre el mismo microciclo.',
    hints: [
      'Seleccioná un día para ver cómo participan las diferentes áreas.',
      'Cambiá la vista para observar la misma semana desde Cuerpo Técnico, Rendimiento o Área Médica.',
      'El partido conecta la planificación con convocatoria, minutos, GPS y análisis posterior.',
    ],
  },
  {
    id: 'rendimiento',
    title: 'Tablero de Rendimiento',
    short: 'Rendimiento',
    route: '/performance/dashboard',
    icon: LayoutDashboard,
    message: 'Toda el área de rendimiento en una vista personal.',
    text: 'Carga externa, carga interna, wellness, evaluaciones y alertas se combinan en widgets editables para cada profesional.',
    hints: [
      'Editá el tablero y elegí qué información priorizar.',
      'Los filtros y la configuración se guardan por usuario, plantel y función.',
      'Las alertas cruzan diferentes fuentes alrededor del jugador.',
    ],
  },
  {
    id: 'carga_externa',
    title: 'Carga externa y GPS',
    short: 'Carga externa',
    route: '/gps',
    icon: Gauge,
    message: 'Una o varias sesiones, desde el plantel hasta cada jugador.',
    text: 'Seleccioná sesiones con GPS, personalizá métricas, creá reglas visuales y construí gráficos dinámicos con etiquetas.',
    hints: [
      'Combiná sesiones para ver el acumulado.',
      'Tocá la foto de un jugador para abrir su carga individual.',
      'Configurá métricas, reglas de color y estilos de gráficos.',
    ],
  },
  {
    id: 'salud',
    title: 'Salud y disponibilidad',
    short: 'Salud',
    route: '/performance/medical',
    icon: Heart,
    message: 'El rendimiento también depende de la salud del jugador.',
    text: 'Conectá información médica, disponibilidad, bienestar y otros indicadores que afectan el día a día.',
    hints: [
      'Lesiones y disponibilidad se siguen desde acá.',
      'El bienestar y otros indicadores se conectan con el rendimiento.',
    ],
  },
  {
    id: 'jugador360',
    title: 'Jugador 360°',
    short: 'Jugador 360°',
    route: '/players',
    icon: UserRound,
    message: 'Toda la historia deportiva del jugador en un solo perfil.',
    text: 'Rendimiento, minutos, evaluaciones, disponibilidad y evolución conectados alrededor del futbolista.',
    hints: [
      'La información de diferentes áreas se relaciona alrededor del mismo jugador.',
      'Abrí un jugador para ver su perfil integral conectado.',
    ],
  },
  {
    id: 'integraciones',
    title: 'Integraciones',
    short: 'Integraciones',
    route: '/demo/integrations',
    icon: Network,
    message: 'Tu club ya tiene herramientas. PerformancePitch las conecta.',
    text: 'La plataforma se adapta a la estructura, metodología y proveedores de cada institución.',
    hints: [],
  },
];