import React from "react";
import { Link2, Pencil, Trash2 } from "lucide-react";
import PlayerPhoto from "@/components/player/PlayerPhoto";

export default function PlayerRosterTable({ rows, onOpen, onShare, onEdit, onDelete, canEdit, canDelete }) {
  if (!rows.length) return <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-12 text-center text-sm text-zinc-500">No hay jugadores que coincidan con los filtros seleccionados.</div>;
  return <div data-tour="players-table" className="overflow-x-auto rounded-2xl border border-zinc-800 bg-zinc-900"><table className="w-full text-sm"><thead><tr className="bg-zinc-950/60 text-left text-xs text-zinc-500"><th className="p-3">Jugador</th><th className="p-3">Nacimiento / edad</th><th className="p-3">Categoría</th><th className="p-3">Posición</th><th className="p-3">Pierna hábil</th><th className="p-3">Peso</th><th className="p-3">Talla</th><th className="p-3">Estado</th><th className="p-3" /></tr></thead>
    <tbody>{rows.map(({ player, categoryName, age, birthYear, height, weight }) => <tr key={player.id} onClick={() => onOpen(player)} className="cursor-pointer border-t border-zinc-800 hover:bg-zinc-800/40"><td className="p-3"><div className="flex items-center gap-3"><PlayerPhoto player={player} className="h-11 w-11 rounded-xl border border-zinc-700 object-cover" fallbackClassName="flex h-11 w-11 items-center justify-center rounded-xl border border-zinc-700 bg-zinc-800" /><div><p className="font-semibold text-white">{player.first_name} {player.last_name}</p><p className="text-xs text-zinc-600">Ver ficha del jugador</p></div></div></td><td className="p-3 text-zinc-300">{birthYear || "—"}<span className="ml-2 text-zinc-600">{age !== null ? `${age} años` : ""}</span></td><td className="p-3 text-zinc-300">{categoryName}</td><td className="p-3 text-zinc-300">{player.position || "—"}</td><td className="p-3"><span className="rounded-full border border-zinc-700 px-2 py-1 text-xs text-zinc-300">{player.dominant_leg || "—"}</span></td><td className="p-3 text-zinc-300">{weight != null ? `${Number(weight).toFixed(1)} kg` : "—"}</td><td className="p-3 text-zinc-300">{height != null ? `${Number(height).toFixed(0)} cm` : "—"}</td><td className="p-3"><span className="rounded-full bg-zinc-800 px-2 py-1 text-xs text-zinc-300">{player.status || "—"}</span></td><td className="p-3"><div className="flex justify-end gap-1" onClick={(e) => e.stopPropagation()}><button data-tour="players-share" onClick={() => onShare(player)} className="p-2 text-zinc-500 hover:text-emerald-400"><Link2 size={15} /></button>{canEdit && <button onClick={() => onEdit(player)} className="p-2 text-zinc-500 hover:text-white"><Pencil size={15} /></button>}{canDelete && <button onClick={() => onDelete(player)} className="p-2 text-zinc-600 hover:text-red-400"><Trash2 size={15} /></button>}</div></td></tr>)}</tbody>
  </table></div>;
}